# Generated by Django 3.2.6 on 2021-08-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_img',
            field=models.CharField(default='Users/aaqib/Documents/al.jpg', max_length=500),
        ),
    ]
